const API_BASE = window.VTC_API_BASE || "http://localhost:8080";
const tabs=document.querySelectorAll(".tab");const scheduleRow=document.querySelector("#scheduleRow");const form=document.querySelector("#bookingForm");const quote=document.querySelector("#quote");let mode="now";let token=localStorage.getItem("vtc_token")||"";
tabs.forEach(tab=>tab.addEventListener("click",()=>{tabs.forEach(t=>t.classList.remove("active"));tab.classList.add("active");mode=tab.dataset.type;scheduleRow.hidden=mode!=="later";}));
function show(message,strong=""){quote.hidden=false;quote.innerHTML=(strong?"<strong>"+strong+"</strong>":"")+message;quote.scrollIntoView({behavior:"smooth",block:"nearest"});}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(token)headers.Authorization="Bearer "+token;const res=await fetch(API_BASE+path,{...options,headers});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||"Erreur API");return data;}
async function authenticate(){if(token)return true;const email=prompt("Votre e-mail :");if(!email)return false;const password=prompt("Votre mot de passe (8 caractères minimum) :");if(!password)return false;try{const login=await api("/api/v1/auth/login",{method:"POST",body:JSON.stringify({email,password})});token=login.token;localStorage.setItem("vtc_token",token);return true;}catch(_){const firstName=prompt("Première connexion — prénom :");const lastName=prompt("Nom :");if(!firstName||!lastName)return false;await api("/api/v1/auth/register",{method:"POST",body:JSON.stringify({email,password,first_name:firstName,last_name:lastName,phone:""})});const login=await api("/api/v1/auth/login",{method:"POST",body:JSON.stringify({email,password})});token=login.token;localStorage.setItem("vtc_token",token);return true;}}
async function geocode(address){const url="https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q="+encodeURIComponent(address);const res=await fetch(url,{headers:{"Accept":"application/json"}});if(!res.ok)throw new Error("Géocodage indisponible");const rows=await res.json();if(!rows.length)throw new Error("Adresse introuvable : "+address);return{lat:Number(rows[0].lat),lng:Number(rows[0].lon)};}
form.addEventListener("submit",async e=>{e.preventDefault();const pickup=document.querySelector("#pickup").value.trim();const dropoff=document.querySelector("#dropoff").value.trim();const service=document.querySelector("#service").value;if(!pickup||!dropoff)return;try{if(!await authenticate())return;show("Recherche des coordonnées et calcul du tarif…");const[from,to]=await Promise.all([geocode(pickup),geocode(dropoff)]);const estimate=await api("/api/v1/pricing/estimate",{method:"POST",body:JSON.stringify({pickup_lat:from.lat,pickup_lng:from.lng,dropoff_lat:to.lat,dropoff_lng:to.lng})});const amount=(estimate.quote.amount_cents/100).toFixed(2).replace(".",",");show(amount+" € · "+estimate.distance_km.toFixed(1)+" km · "+Math.round(estimate.duration_min)+" min<br>Tarif provisoire calculé par l’API Go.","Estimation");const date=document.querySelector("#date").value;const time=document.querySelector("#time").value;if(mode==="later"&&(!date||!time))throw new Error("Choisissez une date et une heure.");const scheduledAt=mode==="later"?new Date(date+"T"+time).toISOString():new Date().toISOString();const booking=await api("/api/v1/bookings",{method:"POST",body:JSON.stringify({pickup_address:pickup,dropoff_address:dropoff,service_type:service,scheduled_at:scheduledAt})});show(amount+" € · réservation #"+booking.id.slice(0,8)+"<br>"+pickup+" → "+dropoff,"Réservation créée");}catch(err){show(err.message,"Impossible de réserver");}});
document.querySelector("#loginBtn").addEventListener("click",async()=>{try{if(token){localStorage.removeItem("vtc_token");token="";alert("Vous êtes déconnecté.");return;}if(await authenticate())alert("Connexion réussie.");}catch(err){alert(err.message);}});
